INPUT:
  IN_CHANNELS: 3
  IMG_SIZE: 224
  SCALE_TRAIN: (0.5, 1.0)
  CROP_PCT_TEST: 0.875
  TO_BGR255: false
  BRIGHTNESS: 0.4
  CONTRAST: 0.4
  SATURATION: 0.4
  HUE: 0.0
  RANDOM_ERASE_PROB: 0.4
  RANDOM_ERASE_MODE: "const"
  AUTO_AUGMENT: ""

DATASETS:
  TRAIN:
  TEST:

DATALOADER:
  NUM_WORKERS: 8

MODEL:
  ARCHITECTURE: "resnet18"
  GLOBAL_POOL: 'avg'
  NUM_CLASSES: 5

SOLVER:
  MAX_EPOCHS: 200
  BATCH_SIZE: 200
  OPTIMIZER: "adam"
  WEIGHT_DECAY: 1e-4
  BASE_LR: 0.001
  SCHEDULER: 'step'
  DECAY_EPOCHS: 60
  WARMUP_EPOCHS: 3
  LABEL_SMOOTHING: 0.1
  EVAL_METRIC: 'prec1'
  CHECKPOINT_PERIOD: 100
  LOG_PERIOD: 20


OUTPUT_DIR: './'
